spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_achievement?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true



mybatis-plus:
  mapper-locations:  classpath*:mapper/*.xml
  type-aliases-package: com.example.crmachievement.entity
  configuration:
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        logic-delete-field: deleted  # 逻辑删除字段
        id-type: auto

jwt:
  secret: YourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHere  # 推荐使用环境变量注入
  expiration: 86400000  # 24小时（单位：毫秒）
  issuer: ExampleApp
  audience: Client